#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl5,  button,         sensorTouch)
#pragma config(Sensor, dgtl8,  pneumatics,     sensorDigitalOut)
#pragma config(Sensor, dgtl11, colorSelector,  sensorTouch)
#pragma config(Sensor, dgtl12, autonomousSelector, sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           leftDrive1,    tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftDrive2,    tmotorVex393, PIDControl, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port3,           leftDrive3,    tmotorVex393, openLoop)
#pragma config(Motor,  port4,           rightDrive1,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           rightDrive2,   tmotorVex393, PIDControl, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port6,           rightIntake,   tmotorVex393, openLoop)
#pragma config(Motor,  port7,           leftLift,      tmotorVex393, openLoop)
#pragma config(Motor,  port8,           rightLift,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           leftIntake,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "ControllerFunctions.c"		//Custom library of functions for controller
#include "Autonomous/AutonomousFunctions.c"	//Custom library of functions for autonomous
#include "Autonomous/AutonomousPrograms.c"	//Custom library of functions for autonomous

//up = 1405
//down = 134
//1 = red
//180 turn = 825


/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	//Reset encoders
	resetEncoders();
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{

	resetEncoders();

	//No position pin = middle zone
	if(!SensorValue[autonomousSelector]){
		//No color pin = blue
		if(!SensorValue[colorSelector])
			blueMiddle();
		//Color pin = red
		else
			redMiddle();
	}

	//Pin = hanging zone
	else{
		//No color pin = blue
		if(!SensorValue[colorSelector])
			blueHanging();
		//Color pin = red
		else
			redHanging();
	}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	//Intake
	while (true)
	{
		if(vexRT(Btn6U)){
			motor[leftIntake] = motor[rightIntake] = 127;
			}else if(vexRT(Btn6D)){
			motor[leftIntake] = motor[rightIntake] = -127;
			}else {
			motor[leftIntake] = motor[rightIntake] = 0;
		}
        //Driving
        //Automatically shut off drive when the joystick has a value of -30 to +30 to avoid stalling and save battery.

        bool leftDriveShouldStop;
        bool rightDriveShouldStop;

        //Set boolean -- left
        if(abs(vexRT[Ch3]) <= 30)
            leftDriveShouldStop = true;
        else
            leftDriveShouldStop = false;

        //Set boolean -- right
        if(abs(vexRT[Ch2]) <= 30)
            rightDriveShouldStop = true;
        else
            rightDriveShouldStop = false;

        //Apply boolean -- left
        if(leftDriveShouldStop)
            motor[leftDrive1] = motor[leftDrive2] = motor[leftDrive3] = 0;
        else
            motor[leftDrive1] = motor[leftDrive2] = motor[leftDrive3] = vexRT[Ch3];

        //Apply boolean -- right
        if(rightDriveShouldStop)
            motor[rightDrive1] = motor[rightDrive2] = 0;
        else
            motor[rightDrive1] = motor[rightDrive2] =  vexRT[Ch2];

		//Lift
		if(vexRT(Btn5U) && SensorValue[armPot] < 80000000){
			motor[port7] = motor[port8] = 127;
			}else if(vexRT(Btn5D) && SensorValue[armPot] > 136){
			motor[port7] = motor[port8] = -127;
			}else{
			motor[port7] = motor[port8] = 0;
		}

		//Pneumatics
		if (vexRT(Btn7U))
			SensorValue[pneumatics] = 1;
		else if (vexRT(Btn7D))
			SensorValue[pneumatics] = 0;
	}
}
